### ISSUE TITLE
Table of contents links does not work

### ISSUE THREAD

**Issue by felipesabino** [zubayr/kafka-nodejs#1]
Table of contents use spaces and upper case characters, which dies not match the anchors created  in the markdown.

For example, section _Lets make some simple changes to exsisting script to handle JSON_ link has the following url: `#Lets make some simple changes to exsisting script to handle JSON.` but it should have `#lets-make-some-simple-changes-to-exsisting-script-to-handle-json` instead

**Comment by zubayr** [comment]
Thanks Felipe,
Have update the Table of content. Now it is working. 

Regards,
Zubair AHMED.

**Comment by felipesabino** [comment]
@zubayr :+1: 

Oh, FYI, I have made an working example with Node.js + Express + Kafka + Mongodb using Docker for Kafka instead of having to install is manually, I guess it might be useful: https://github.com/felipesabino/nodejs-express-kafka-mongodb

PS: I know sending message via gh issue is not the best practice but you gh profile and website have no contact information :p
I also have some question regarding kafka and node in production, please let me know if you are available at felipe@sabino.me or [@felipesabino](http://twittew.com/felipesabino)

**Comment by zubayr** [comment]
@felipesabino Nice work. Thanks. 

Here is my email : zubayr.a@gmail.com

Kafka is scaled up and handled very well in production.
We had few issues with load using Node.js.
